apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv05
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/minishift/miq-assets
  persistentVolumeReclaimPolicy: Recycle
